/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#define ALIAS_BASE 0x22000000U //U means unsgined number
#define BITBAND_BASE 0x20000000U //U means unsigned number

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    //Step 1 - create a pointer variable that points to the address of the lecture problem/exercise
	uint8_t *ptr = (uint8_t*)0x20000200;

	*ptr = 0xff; //Initialize the value at our memory location with some value whose 7th bit we will try and clear

	//normal method of read, modify, store (in assembly)
	*ptr &= ~(1 << 7);

	*ptr = 0xff; //Reset the value at the target memory location

	//but band method
	uint8_t *alias_addr = (uint8_t*)(ALIAS_BASE + (32*(0x20000200 - BITBAND_BASE)) + 7*4);

	*alias_addr = 0;





	/* Loop forever */
	for(;;);
}
